version: "3"

services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    env_file:
      - .env.docker
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
  backend:
    build:
      context: backend
    ports:
      - "5000:5000"
