version: '3'
services:
  # db:
  #   image: mysql:8
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_DATABASE: the_video_project
  #     MYSQL_ROOT_PASSWORD: root
  backend:
    build:
      context: backend
    ports:
      - "5000:5000"